name: Build and Publish ARM64 Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Build and push Docker image
        run: |
          export IMAGE_NAME=ghcr.io/${{ github.repository }}
          docker buildx build \
            --platform linux/arm64 \
            --push \
            --tag "$IMAGE_NAME:latest" .

      - name: Start and update containers
        run: |
          docker compose up -d
          sleep 10  # Ensure services start
          docker compose restart
